name: Auto-Update Folder Tree in README

on:
  push:
    branches:
      - master  # Change if your default branch is 'main'

jobs:
  update-readme-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate folder tree (Zabbix_Notes only) and update README
        run: |
          TREE=$(tree Zabbix_Notes -I '.git|node_modules' -L 3)

          awk -v tree="$TREE" '
            /<!-- TREE_START -->/ { print; print "```"; print tree; next }
            /<!-- TREE_END -->/ { print "```"; flag=0; next }
            !flag
          ' Zabbix_Notes/README.md > Zabbix_Notes/README.tmp && mv Zabbix_Notes/README.tmp Zabbix_Notes/README.md


      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update folder tree in README.md"
