name: Auto-Update Folder Tree in README

on:
  push:
    branches:
      - master  # Change if your default branch is 'master' or something else

jobs:
  update-readme-tree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate folder tree and update README
      run: |
        TREE=$(tree -I '.git|node_modules' -L 3)

        awk -v tree="$TREE" '
          /<!-- TREE_START -->/ { print; print "```"; print tree; next }
          /<!-- TREE_END -->/ { print "```"; flag=0; next }
          !flag
        ' README.md > README.tmp && mv README.tmp README.md

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: auto-update folder tree in README.md"
