name: Auto-Update Folder Tree in README

on:
  push:
    branches:
      - master  # Change if your default branch is 'main'

jobs:
  update-readme-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Zabbix_Notes folder tree and update README
        run: |
          # Generate just the Zabbix_Notes structure
          tree Zabbix_Notes -I '.git|node_modules' -L 3 > Zabbix_Notes/folder_tree.txt

          # Replace section in README using clean output
          awk '
            BEGIN { inside=0 }
            /<!-- TREE_START -->/ { print; print "```"; while ((getline line < "Zabbix_Notes/folder_tree.txt") > 0) print line; inside=1; next }
            /<!-- TREE_END -->/   { print "```"; inside=0 }
            inside == 0
          ' Zabbix_Notes/README.md > Zabbix_Notes/README.tmp && mv Zabbix_Notes/README.tmp Zabbix_Notes/README.md



      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update folder tree in README.md"
